spring.application.name=bankcards

# Настройки подключения к PostgreSQL в Docker
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/bank_cards
spring.datasource.username=postgres
spring.datasource.password=secret_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Активируем Liquibase с новым YAML мастер-файлом
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/migration/db.changelog-master.yaml
